first commit
gaurangkeskar/STLtoDAT_translator pull request #1
Opened 2024-10-08 06:35 UTC by gaurangkeskar

2024-10-09 10:44 UTC, cctechyashdoshi commented on headers/Reader.h
You can remove the "using namespace std;" as it's not needed

2024-10-09 10:50 UTC, cctechyashdoshi commented on src/Reader.cpp
the code seems hard coded, especially this part of code👇

data += line.substr(getPos + 7);

2024-10-09 10:51 UTC, cctechyashdoshi requested changes
I have added some corrections, please look through.

2024-10-10 14:05 UTC, gaurangkeskar commented on headers/Reader.h
reader.cpp will throw errors if i remove it.

2024-10-11 13:28 UTC, merged